name = "usaco_green_agent"
description = "The assessment hosting agent for USACO programming problems."
version = "0.1.0"

defaultInputModes = ["text"]
defaultOutputModes = ["text"]
[capabilities]
streaming = false

[[skills]]
id = "host_assess_usaco"
name = "USACO assessment hosting"
description = """
Assess the programming ability of an agent using USACO problems.
"""
tags = ["green agent", "assessment hosting", "usaco", "programming"]
examples = ["""
Your task is to evaluate a USACO problem solution from the agent located at:
<white_agent_url>
http://localhost:9002/
</white_agent_url>
You should use the following problem configuration:
<problem_config>
{
  "problem_name": "ride",
  "timeout_seconds": 2
}
</problem_config>
    """]
